/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void testConnection() {
        // Aquí podrías probar si la conexión a la base de datos funciona
        // O cualquier otro comportamiento que esperes de la clase App
        // Por ejemplo:
        App app = new App();
        assertNotNull(app, "App instance should be created");
    }
}

